name = "corporate-portfolio"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "corporate-portfolio-db"
database_id = "91951ce5-4e9c-4d1a-8f64-00a580866dda"
